name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show  

    # - name: Azure CLI script
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       # Set variables
    #       resourceGroupName="stalin-tf-state-rg"
    #       storageAccountName="stalintfstatesa"
    #       storageContainerName="tfstate"
    #       location="centralindia"
    
    #       # Check if resource group exists
    #       if [ $(az group exists --name $resourceGroupName --output tsv) == false ]; then
    #         # Create resource group if not exists
    #         az group create --name $resourceGroupName --location $location
    #       fi
    
    #       # Check if storage account exists
    #       if [ $(az storage account check-name --name $storageAccountName --output tsv --query 'nameAvailable') == "true" ]; then
    #         # Create storage account if not exists
    #         az storage account create --name $storageAccountName --location $location --resource-group $resourceGroupName --sku Standard_LRS
    #       fi
    
    #       # Check if storage container exists
    #       if [ $(az storage container exists --account-name $storageAccountName --name $storageContainerName --output tsv) == false ]; then
    #         # Create storage container if not exists
    #         az storage container create --account-name $storageAccountName --name $storageContainerName --public-access off
    #       fi
        
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      run: terraform init      

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan 
     
    - name: Terraform Apply
      run: terraform apply -auto-approve 
